### ISSUE TITLE
Autocomplete not returning full results set

### ISSUE THREAD

**Issue by cmcfadden** [UMN-LATIS/bluesheet#22]
dev:
![Screenshot 2023-07-14 at 11 04 37 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/df543d7c-2a97-4d54-b4af-20ef434d5138)

Prod:
![Screenshot 2023-07-14 at 11 05 17 AM](https://github.com/UMN-LATIS/bluesheet/assets/211655/ac906530-9c52-4dbc-8831-a06a6825d766)

**Comment by jxjj** [comment]
They were there with 10rem max height and overflow: auto. I think you understandably weren't seeing it because a 10rem max height almost perfectly aligned with 4 items (and maybe scroll is only set to show while scrolling on your mac?)

Anyway, removed max-height. Updated on dev:

<img width="525" alt="ScreenShot 2023-07-18 at 20 45 42@2x" src="https://github.com/UMN-LATIS/bluesheet/assets/980170/aae9a4b2-cdfb-432c-8384-c0724b483d47">
